<?php


namespace Zngue\User\Http\Request;


use Zngue\User\Helper\ApiFromRequest;

class LoginRequest extends ApiFromRequest
{
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}
