<?php


namespace Zngue\User\Http\Request;


use Illuminate\Routing\Route;
use Zngue\User\Helper\ApiFromRequest;


class RoleRequest extends ApiFromRequest
{

    public function messages()
    {
        if ($this->name=='role.status'){
            return $this->roleStatusMessage();
        }
        if ($this->name=='role.roleDel'){
            return $this->roleDelMessage();
        }
        if ($this->name=='role.editRole') {
            $a = $this->roleEditMessage();
        }
        return parent::messages(); // TODO: Change the autogenerated stub
    }
    public function roleEditMessage(){
        return [

            'status.required'=>':attribute 不能为空',
            'status.numeric'=>':attribute 必须为数字'
        ];
    }
    public function roleDelMessage(){
        return [
            'id.required' => ':attribute 不能为空',
            'id.numeric' => ':attribute 必须为数字',
        ];
    }
    public function roleStatusMessage(){

        return [
            'id.required' => ':attribute 不能为空',
            'id.numeric' => ':attribute 必须为数字',
            'status.required'=>':attribute 不能为空',
            'status.numeric'=>':attribute 必须为数字'
        ];

    }
    public function rules()
    {
        if ($this->name=='role.status'){
            return $this->roleStatusRules();
        }
        if ($this->name='role.roleDel'){
            return $this->roleDelRules();
        }
        if ($this->name=='role.editRole'){
            return $this->roleEditRules();
        }
        return parent::rules(); // TODO: Change the autogenerated stub
    }
    public function roleEditRules(){

        return [
                'status'=>'required|numeric'
            ] ;
    }
    public function roleStatusRules(){

        return [
            'id' => 'bail|required|numeric',
            'status'=>'required|numeric'
        ];
    }

    public function roleDelRules(){
        return [
            'id' => 'bail|required|numeric',
        ];
    }


}
